name: deep_rl_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - gymnasium[atari,classic-control,accept-rom-license,mujoco]==0.29.1
      - mujoco==3.1.4
      - pybullet
      - stable-baselines3==2.6.0
      - matplotlib
      - moviepy==1.0.3
      - numpy<2
      - opencv-python==4.10.0.84
      - torch==2.5.0
      - torchvision==0.20.0
      - torchrl==0.6.0
      - pytorch-ignite==0.5.1
      - tensorboard==2.18.0
      - mypy==1.8.0
      - ray[tune]==2.37.0
      - pytest
      - ipykernel
      - gym-notebook-wrapper

